### ISSUE TITLE
Problem after installing

### ISSUE THREAD

**Issue by jonasvanderhaegen** [GrahamCampbell/Laravel-HTMLMin#17]
After I install laravel 5 and this via composer and add the two lines at config -> app I'm getting errors like: BadMethodCallException in ServiceProvider.php line 111: Call to undefined method [package]

at ServiceProvider->__call('package', array('graham-campbell/htmlmin', 'graham-campbell/htmlmin', 'C:\xampp\htdocs\vdhjonas\laravel\vendor\graham-campbell\htmlmin\src')) in HTMLMinServiceProvider.php line 46

So whatever view or url request I do I get this and when I use the command line 'php artisan publish:config graham-campbell/htmlmin'  -> same error. 
I used this line: composer create-project laravel/laravel test-laravel-5-project dev-develop --prefer-dist
for installing laravel 5. So can someone help me or get this fixed? thanks in advance.

**Comment by GrahamCampbell** [comment]
Yeh, this is a know issue. Laravel 5 doesn't currently support packages.

**Comment by GrahamCampbell** [comment]
You can use an old version of laravel 5 for now by adding this to your composer.json file:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/GrahamCampbell/framework"
        }
    ],
```

**Comment by jonasvanderhaegen** [comment]
L5 is stable now ;)

**Comment by GrahamCampbell** [comment]
I fixed this a long time ago anyway. :)
