### ISSUE TITLE
HTMLMin not working for Laravel 4.2

### ISSUE THREAD

**Issue by ziming** [GrahamCampbell/Laravel-HTMLMin#20]
Hi,

I'm not sure if this is a problem with laravel or your package or mine.

Well all along I have been using laravel-html-minify until recently where I discovered that it just stopped working, no errors but when view source, nothing gets minified. So I deleted the compiled view files at storage/views.

But the problem pesist. So I decided to switch to HTMLMin. Had the same problem as well. blade option true, didn't see minification happen.

For live option true, all I see is all the space on the left are trimmed away, but everything that is on that line still stays on the same line.

I'm not sure if it helps to show you my composer.json to see if anything conflict with yours

```
    "require": {
        "laravel/framework": "4.2.*",
        "graham-campbell/markdown": "~2.0",
        "maatwebsite/excel": "1.*",
        "watson/validating": "0.10.*",
        "guzzlehttp/guzzle": "~4.0",
        "jenssegers/agent": "~2.1",
        "barryvdh/laravel-dompdf": "0.4.*",
        "frozennode/administrator": "dev-master",
        "graham-campbell/throttle": "~2.0",
        "propaganistas/laravel-phone": "~1.2",
        "pubnub/pubnub": "~3.7",
        "aloha/twilio": "dev-master",
        "antoineaugusti/laravel-easyrec": "0.5.2",
        "iron-io/iron_mq": "~3.0",
        "graham-campbell/htmlmin": "~2.0",
        "roave/security-advisories": "dev-master"
    },
    "require-dev": {
        "way/generators": "~2.0",
        "barryvdh/laravel-ide-helper": "~1.11",
        "barryvdh/laravel-debugbar": "~1.8",
        "phpunit/phpunit": "4.5.*"
    },
```

Thank you.

**Comment by GrahamCampbell** [comment]
> But the problem pesist. So I decided to switch to HTMLMin. Had the same problem as well. blade option true, didn't see minification happen.

That's probably because the file you were trying to minify had forbidden html tags, where by it's not safe for us to apply blade minification. You can enable the force option to bypass my checks if you want.

**Comment by GrahamCampbell** [comment]
> For live option true, all I see is all the space on the left are trimmed away, but everything that is on that line still stays on the same line.

Can you show me? I suspect it's because it's not safe for us to minify, or maybe because the incorrect content type is set?

**Comment by ziming** [comment]
Hi @GrahamCampbell 

I tried the force option and it worked.

Upon turning force to false, it no longer works.

So I begin to investigate if there is a problem with my friends html, I managed to spot a number of them however there is also quite a number of pages which passes the W3C htm5 validator test perfectly, the only errors being those introduced by laravel debug bar. So I disabled laravel debug bar. Clear storage/views. But all those pages still doesn't get minified.

**Comment by GrahamCampbell** [comment]
> Upon turning force to false, it no longer works.

Yes, you need to leave force on for that to work. I'd recommend not doing that. I'm not minifying those pages for good reason. They will actually behave differently when minified.

**Comment by ziming** [comment]
@GrahamCampbell but if they all passes HTML Validation, what could possibly cause them to not minify?

**Comment by GrahamCampbell** [comment]
> but if they all passes HTML Validatior test, what could possibly cause them to not minify?

I'm not saying it gives invalid html. Example: you have some inline javascript - we would break that in some cases if we minified it as blade, so we still any files with script tags.

Another example: if you have <code> blocks in your file, you don't want their contents minifed, do you?
