### ISSUE TITLE
Support for custom Blade tags

### ISSUE THREAD

**Issue by ashjmcfox** [GrahamCampbell/Laravel-HTMLMin#22]
I am developing an application using AngularJS and need to modify the Blade content tags from the default ```{{ }}``` to avoid clashes.

```php
Blade::setRawTags('@<%', '%>');
Blade::setContentTags('<%', '%>');
Blade::setEscapedContentTags('<%%', '%%>');
```

This seems to work fine with a clean install of Laravel 5, but not when using this package. The minifier seems to ignore these options completely.

Any suggestions?

Thanks.

**Comment by GrahamCampbell** [comment]
You need to make sure you set these tags AFTER I change the blade compiler with my version.

**Comment by GrahamCampbell** [comment]
Basically, you must set the tags after my services provider has booted.

https://github.com/GrahamCampbell/Laravel-HTMLMin/blob/master/src/HTMLMinServiceProvider.php#L66

**Comment by ashjmcfox** [comment]
Now working. Thought it might be something stupid I was doing. Thanks!

**Comment by insign** [comment]
Hi, I'm using it too:
```php
		Blade::setRawTags('{{', '}}');
		Blade::setContentTags('{{{', '}}}');
		Blade::setEscapedContentTags('{{{', '}}}');
```
This lines are in the the register() method of AppServiceProvider.

For where I need to move these lines to it work in my custom blade tags?

**Comment by GrahamCampbell** [comment]
Move them to boot.
