### ISSUE TITLE
Filter: undefined method

### ISSUE THREAD

**Issue by ntopulos** [GrahamCampbell/Laravel-HTMLMin#23]
I would like to minify a group of routes.
As suggested in the [readme](https://github.com/GrahamCampbell/Laravel-HTMLMin#filters) (there is no more filters in Laravel 5), I added "htmlmin" as a middleware to this group:
``` 'middleware'    => ['htmlmin'] ```

But instead of a minification, I get this error:
```
FatalErrorException in Pipeline.php line 125:
Call to undefined method GrahamCampbell\HTMLMin\HTMLMin::handle()```

Did I done something wrong ?

**Comment by GrahamCampbell** [comment]
No, that's not how this works. We are using a filter, and this package automatically applies to to ALL routes for you, if you enabled live minification.

**Comment by GrahamCampbell** [comment]
`'htmlmin'` is not a middleware...

**Comment by ntopulos** [comment]
Ok thanks, I get it now.

**Comment by GrahamCampbell** [comment]
> there is no more filters in Laravel 5

Also, the are filters in L5, and you can still use that filter if you want, actually.

**Comment by GrahamCampbell** [comment]
Allowing you to individually minify routes. The documentation on my readme is exclusively for L5. All of it is correct, and up to date.

**Comment by GrahamCampbell** [comment]
Look at our tests: https://github.com/GrahamCampbell/Laravel-HTMLMin/blob/master/tests/Functional/FilterEnabledTest.php. That;s how you can use our filter.
