### ISSUE TITLE
These elements created a bug in the blade minifier

### ISSUE THREAD

**Issue by hosseinhkj** [GrahamCampbell/Laravel-HTMLMin#25]
```html
<!--[if IE 8]> <html lang="{{Lang::getLocale()}}" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="{{Lang::getLocale()}}" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="{{Lang::getLocale()}}">
<!--<![endif]-->
```

These elements broke down the HTML Minifier

**Comment by GrahamCampbell** [comment]
What you you mean by broke? Do you mean it changed the behaviour of the code, or just didn't minify it. If it didn't minify it, that's probably expected. We skip files that are risky.

**Comment by hosseinhkj** [comment]
It minifies but fails to do it on these elements breaking the whole minification so a blank page is displayed and the HTML source has turned red after these elements.

**Comment by GrahamCampbell** [comment]
Hmmm, could you show me please?

**Comment by hosseinhkj** [comment]
I'm really sorry for the confusion I created, it seems that it was a problem with my closing tag. I hadn't eyed a small typo.
