### ISSUE TITLE
Example of CSS and JS minifier

### ISSUE THREAD

**Issue by hosseinhkj** [GrahamCampbell/Laravel-HTMLMin#26]
I know this sounds silly but this is what I found out from the API and other documentations of how to use the CSS Minifier which isn't working. Please guide me on how (and where) to use the correct code (what code exactly).

```html
<link href="{!!HTMLMin::css('/themes/bootstrap/assets/global/css/components.css')!!}" rel="stylesheet">
```

**Comment by GrahamCampbell** [comment]
Oh, right, you can't use it like this. That method accept your actual css, rather than a path to it.

**Comment by GrahamCampbell** [comment]
This method was designed so people can use it in their own asset management tools and the like.

**Comment by hosseinhkj** [comment]
So how does the CSS and JS minification work? or it doesn't have these functions?

**Comment by GrahamCampbell** [comment]
You pass your actual css as a string to the method, and it returns minified css as a string.

**Comment by GrahamCampbell** [comment]
Look at my tests. They tell you how the code works: https://github.com/GrahamCampbell/Laravel-HTMLMin/blob/master/tests/Minifiers/CssMinifierTest.php#L24.
