### ISSUE TITLE
Incompatibility when extending blade ?

### ISSUE THREAD

**Issue by potsky** [GrahamCampbell/Laravel-HTMLMin#27]
Hello,

everything works fine at compilation time but when I register my Service Provider which adds a new blade word, it does not work anymore.

Here is my extend :

```
Blade::extend(function($view, $compiler)
{
    $pattern = $compiler->createMatcher('alternate');
    return preg_replace($pattern, "$1<?php echo app('blade.alternator')->choose$2 ?>", $view);
});
```

In your service provider, if I add 2 debug lines :

```
    protected function enableBladeOptimisations()
    {
        $app = $this->app;
error_log('coucou1');
        // register a new engine
        $app['view']->getEngineResolver()->register('blade', function () use ($app) {
            $compiler = $app['htmlmin.compiler'];
error_log('coucou2');
            return new CompilerEngine($compiler);
        });

        // add the extension
        $app->view->addExtension('blade.php', 'blade');
    }
```

only `coucou1` is displayed and not `coucou2`. If I remove my extend, `coucou2`is displayed at compilation time.

Do I extend blade not correctly ? (based on <http://laravel.com/docs/4.2/templates#extending-blade>)

**Comment by GrahamCampbell** [comment]
Make sure you extend in your boot method, and that you register your service provider AFTER mine. :)

**Comment by potsky** [comment]
Already after but in the register method... It works at boot method, thanx!

**Comment by GrahamCampbell** [comment]
Yeh, you should always use the boot method when you're relying on services registered by other service providers. :)

**Comment by potsky** [comment]
Thank you for your great laravel packages, they are so clean and useful :-) Thanx!

**Comment by GrahamCampbell** [comment]
No problem. :)
