### ISSUE TITLE
How to minify JS/CSS

### ISSUE THREAD

**Issue by MichealMi** [GrahamCampbell/Laravel-HTMLMin#28]
Hello,
I haven't found a way to contact you elsewhere. I'm not to long into Laravel and I don't understand how to minify JS/CSS. The HTML minification works like a charme. But how to minify a stylesheet?

**Comment by GrahamCampbell** [comment]
We don't provide a way to pipe your css/js through a minifier automatically as the user requests it. Use laravel elixer, or write your own way of doing it using the provided methods. I've no plans to add this to the cores as everyone as their own way of dealing with assets.
