### ISSUE TITLE
Minify Whitespace for Blade

### ISSUE THREAD

**Issue by drtzack** [GrahamCampbell/Laravel-HTMLMin#29]
It's not stripping whitespaces for blade templates.

	<!DOCTYPE html> <html> <head> <meta charset="utf-8"> <title></title> 

But it's okay for live.

**Comment by GrahamCampbell** [comment]
We don't strip it all, incase it changes the way it displays. We always leave one whitespace char. If you want maximum results, use our live minifier. It'll really make it small. :)

**Comment by drtzack** [comment]
Yeah but live tooks so much time. Is there any chance to put an config option?

**Comment by GrahamCampbell** [comment]
> Is there any chance to put an config option?

Not sure what you mean?

**Comment by GrahamCampbell** [comment]
If I removed all spaces, your content will be totally broken...

**Comment by drtzack** [comment]
It's not broken for live.

I mean an option like blade, force or live. That will make full minify.

**Comment by GrahamCampbell** [comment]
It already is minifying as much as possible. If we did anything more, all your text would look like this:

```
thequickbrownfoxjumpedoverthelazydog
```
