### ISSUE TITLE
Custom Blade Directives Do Not Get Rendered

### ISSUE THREAD

**Issue by mattisdada** [GrahamCampbell/Laravel-HTMLMin#30]
With blade minification turned on, any custom directives just get turned into plain text, example:

**Blade Minification On**
![image](https://cloud.githubusercontent.com/assets/314500/8047999/b3f65bb6-0e8f-11e5-8e83-a5a6b7eab73d.png)

**Blade Minification Off**
![image](https://cloud.githubusercontent.com/assets/314500/8048021/dd7fc616-0e8f-11e5-91e9-d6437050a031.png)

The force option doesn't seem to affect the behavior....

**Comment by GrahamCampbell** [comment]
You need to register your custom blade stuff in your BOOT method, not in register.

**Comment by antriver** [comment]
For anybody coming here with the same issue:
My custom blade directives were defined in the boot() method of a ServiceProvider but were still not being rendered in the minified output.
Make sure your ServiceProvider that adds those custom directives appears AFTER 'GrahamCampbell\HTMLMin\HTMLMinServiceProvider' in your app.providers config.
