### ISSUE TITLE
Possible to keep a comment?

### ISSUE THREAD

**Issue by elliotlings** [GrahamCampbell/Laravel-HTMLMin#32]
Is there a way to stop a HTML comment from being removed?

**Comment by GrahamCampbell** [comment]
Yes. Don't use the minifier?

**Comment by GrahamCampbell** [comment]
Sorry, I just don't understand your question.

**Comment by joexanderson** [comment]
@GrahamCampbell I am interested in doing this as well. For my blade views, I'd like to keep a single copyright/attribution comment at the top for those who are looking at the source. Is there a way to tell the minifier to ignore comments?
