### ISSUE TITLE
htmlmin.php not generated

### ISSUE THREAD

**Issue by bhargav3** [GrahamCampbell/Laravel-HTMLMin#34]
I installed this package and ran `php artisan vendor:publish` and I get the message `Nothing to publish.`

Any idea how to fix this?

**Comment by vinkla** [comment]
Did you register the service provider in `config/app.php`?

```
'GrahamCampbell\HTMLMin\HTMLMinServiceProvider'
```

**Comment by bhargav3** [comment]
Yes, I did that.

**Comment by GrahamCampbell** [comment]
Did you clear laravel's config cache?

**Comment by bhargav3** [comment]
That was it, thanks @GrahamCampbell @vinkla

**Comment by bhargav3** [comment]
@GrahamCampbell I have set `'blade' => true` but I see the html is not compressed. Is there any anything else I need to do? I'm rendering html using `view` function.
