### ISSUE TITLE
master blade template is not minified

### ISSUE THREAD

**Issue by rogervila** [GrahamCampbell/Laravel-HTMLMin#38]
Hello,

I have a 'master.blade.php' file that includes the rest of the templates inside the body tag.
Those templates are minified, but not the master one.

I have both options, 'blade' and 'force' with TRUE value.

As you see in the image, the code inside the body tag occupies one line, but not the rest of the code.

![captura de pantalla 2015-09-15 a la s 20 06 21](https://cloud.githubusercontent.com/assets/6053012/9885570/1bc71fd4-5be6-11e5-8e0b-2013d4df4bda.png)

I am the only one with this problem, or is this a bug?

Thank you.

**Comment by GrahamCampbell** [comment]
Did you clear your compiled blade files before starting otherwise it won't be compiled again and minified.

**Comment by rogervila** [comment]
I have reinstalled the service and now it works perfect.
I don't understand what happened, but the issue can be closed.

Thank you for your time.
