### ISSUE TITLE
Disable minification on specific routes

### ISSUE THREAD

**Issue by rogervila** [GrahamCampbell/Laravel-HTMLMin#41]
Hello, I would like to know if there is a way to disable htmlmin in specific routes.
I am creating some txt files with blade, and the minification is breaking the markup.

Thank you very much!

**Comment by GrahamCampbell** [comment]
Disabling blade minification is not possible in that way because it's totally got nothing to do with routing.

**Comment by GrahamCampbell** [comment]
Disabling the minification middleware is possible though.

**Comment by GrahamCampbell** [comment]
There is a way to manually skip minifying a file though, through hacky means. Just include some content that we can't minfy so we skip the whole file.

**Comment by GrahamCampbell** [comment]
Anything that matches this: https://github.com/GrahamCampbell/Laravel-HTMLMin/blob/master/src/Minifiers/BladeMinifier.php#L83.

**Comment by GrahamCampbell** [comment]
Though, tbh, it would be cool if you could send a PR to that function to get it to recognize your use case and skip such cases.

**Comment by rogervila** [comment]
Thank you @GrahamCampbell 
I was planning to extend the BladeMinifier class but adding the dangerous tags in a blade comment did the trick.
```

txt content
lorem ipsum

{{--

<code></code>
<textarea></textarea>
<pre></pre>

--}}

```

**Comment by GrahamCampbell** [comment]
Bit of a hack though. I wonder if I should add a way to exclude files by config?

**Comment by rogervila** [comment]
Maybe it could be possible with a custom blade directive, that could output a string recognized in the `shouldMinify()` preg_match function.

**Comment by GrahamCampbell** [comment]
> Maybe it could be possible with a custom blade directive

Yeh, but that's no better than just putting that comment hack in the file tbh.
