### ISSUE TITLE
Minification breaks extensions from a package

### ISSUE THREAD

**Issue by TheAliAbbasi** [GrahamCampbell/Laravel-HTMLMin#46]
while using this package which is perfect, thank you by the way, I seem to have a little problem:
when I use https://github.com/RobinRadic/blade-extensions to extend my blade directives they don;t get compiled in the process, I can't find the problem myself, or even it's a bug or not. I was thinking you could take a look at this if you have time

**Comment by GrahamCampbell** [comment]
You need to clear out the compiled blade files.

**Comment by TheAliAbbasi** [comment]
I actually did that, a few times :-)

**Comment by GrahamCampbell** [comment]
Looks like a bug in blade-extensions. They're being naughty with services providers.

**Comment by TheAliAbbasi** [comment]
I extended blade myself without blade extensions package and again my extensions doesn't work with HTMLMin

**Comment by GrahamCampbell** [comment]
Probably because your extending in register instead of boot.

**Comment by GrahamCampbell** [comment]
Example of a service provier that works just fine with htmlmin: https://github.com/BootstrapCMS/CMS/blob/master/app/Providers/AppServiceProvider.php.

**Comment by emielmolenaar** [comment]
Having the same problem here with custom directives. It seems that de Blade instance is overwritten with a custom one, losing all directives.

**Comment by GrahamCampbell** [comment]
Surely just making sure our service provider is registered before other ones that define directives will work?

**Comment by emielmolenaar** [comment]
In my case, the directives are defined in `AppServerProvider::boot` and the HTMLMin service provider is added in `config/app.php` .

**Comment by GrahamCampbell** [comment]
Is that service provider registered after the htmlmin one?
