### ISSUE TITLE
shouldMinify ignores @shield

### ISSUE THREAD

**Issue by dsfser** [GrahamCampbell/Laravel-HTMLMin#47]
hello,

i found a problem with this script.

i use defender for laravel and it uses @shield and @endshield

but the shouldMinify ignores this and prints the @shield as text on the web page.

what do i need to add to shouldMinify to fix this problem?

**Comment by GrahamCampbell** [comment]
Sounds like this other package is doing something wrong to cause this bug. Please take it up with them.
