### ISSUE TITLE
Mess the email views

### ISSUE THREAD

**Issue by insign** [GrahamCampbell/Laravel-HTMLMin#48]
Unfurtunally, the package mess with the html email when automatic compile is enabled.

There is anyway to disable it on email views?

**Comment by GrahamCampbell** [comment]
You can just include anything that'll match https://github.com/GrahamCampbell/Laravel-HTMLMin/blob/master/src/Minifiers/BladeMinifier.php#L83 in the files.

I do plan to add a way to skip files by name soon though, say like `email.*`.

**Comment by GrahamCampbell** [comment]
> Unfurtunally, the package mess with the html email when automatic compile is enabled.

Do you have force mode one, because it shouldn't break stuff otherwise?

**Comment by insign** [comment]
I tried without force mode, but still breaking... I'm using a email template that uses a lot of code and css to make it works fine in any device.

Thanks, I'll wait for this new feature.

**Comment by GrahamCampbell** [comment]
> I tried without force mode, but still breaking

Did you clear the view cache after changing the config?

**Comment by palpalani** [comment]
We didn't get any issues. but we don't want to minify each email, because we send thousands of emails daily.
