### ISSUE TITLE
Not every view is being compiled.

### ISSUE THREAD

**Issue by Kiszko** [GrahamCampbell/Laravel-HTMLMin#50]
Hey there, nice package.

So when enabling 'Automatic Blade Optimisations' maybe 80% of my views compile.
The others, refuse to. So after some playing around I found that, indeed, 'Force Blade Optimisations' will 100% minify the views.

My question is why should it be 'USED WITH CAUTION', I don't really understand the potential security threats there, when all it's essentially doing is removing whitespace.

Also how can I compose a view so that I do not need to use the force setting? Like all the html validates fine, so what is it that's causing the view to refuse to be minified. Do I even need to be weary of the forced blade optimisations?

So yeah if you could expand on what the differences are amongst those settings, that'd be sweet.

Luka

**Comment by GrahamCampbell** [comment]
There are no security issues with doing that. You just can't remove all the whitespace because it will actually change the output. Say, if you had `pre` tags.

**Comment by GrahamCampbell** [comment]
You can enable live minification using the middleware provided here if you want to minify the html output at runtime each time. That will give you the smallest results.

**Comment by Kiszko** [comment]
I don't really see any benefits in live minification? As I wouldn't want to reprocess on every page load, a one off compiled view is fine.

Okay I'll continue on with hardcode mode.

**Comment by Kiszko** [comment]
Turns out this was the information I was looking for:

https://github.com/GrahamCampbell/Laravel-HTMLMin/issues/16

:)
