### ISSUE TITLE
Flattening <pre> tags with newlines in them

### ISSUE THREAD

**Issue by dlai286** [GrahamCampbell/Laravel-HTMLMin#52]
I have a blade file that contains a `<pre>` tag, however this package will flatten:

```
<pre>
foo
bar
</pre>
```
into a single line `foo bar` disregarding the newline. Is there any way to fix this?

**Comment by GrahamCampbell** [comment]
This is known. This is why we don't minify files like that. It's doing this because you've turned on forced mode. Forced mode may break files.
