### ISSUE TITLE
WARN: using htmlmin besides artesaos/defender and other packages

### ISSUE THREAD

**Issue by NoviCMS** [GrahamCampbell/Laravel-HTMLMin#54]
Hello,

i have found a bug when using GrahamCampbell/Laravel-HTMLMin and artesaos/defender together.

artesaos/defender registers some custom blade directives like @shield and @endshield... when using the option "Automatic Blade Optimizations" the directives will be printed instead of replaced by php code.

**Comment by GrahamCampbell** [comment]
Looks like that package is registering them in the wrong place. It must do it in boot, not register,
