### ISSUE TITLE
New lines removed causing text between tags to be bunched together

### ISSUE THREAD

**Issue by bridgeport** [GrahamCampbell/Laravel-HTMLMin#55]
First off, thanks for this package. I did notice some strange inconsistency that's causing some new lines to be removed and replaced with nothing.

Using Laravel 5.2.43, Laravel-HTMLMin 4.3,PHP 7.0.9, blade compilation disabled, live compilation via middle is active.

It's easier to just provide the reproducible code:

Example 1: Current, correct minification:
```html
<p>Hello
<b>World</b></p>
```

Gets minified as:
```html
<p>Hello
<b>World</b></p>
```

There's no change, which is good. The intentional line break before the opening bold `<b>` tag is honored.

Example 2: Incorrect minification (notice the extra line break in the middle):
```html
<p>Hello

<b>World</b></p>
```

Gets minified to this:
```html
<p>Hello<b>World</b></p>
```

The two words get bunched together, new line eliminated, and there's not even a space separating Hello and World. This changes the layout, and the actual wording from `Hello World` to `HelloWorld`

I'm just using the bold `<b>` tag as an example. This happens with other tags as well.

Thanks.

**Comment by GrahamCampbell** [comment]
Yeh, it's not perfect. You'll get best results using our minifier middleware rather than the blade minifier.

**Comment by bridgeport** [comment]
> Yeh, it's not perfect. You'll get best results using our minifier middleware rather than the blade minifier.

Thanks for getting back. That's odd. I thought that's what I was doing.

In `/config/htmlmin.php` I had
```php
return [
    'blade' => false,
    'force' => false,
];
```

And this within `routes.php`:
```php
Route::get('/', function () {
    return view('index');
})->middleware(['GrahamCampbell\HTMLMin\Http\Middleware\MinifyMiddleware']);
```

Also tried this:
```php
Route::get('/', ['middleware' => ['GrahamCampbell\HTMLMin\Http\Middleware\MinifyMiddleware'], function () {
    return view('index');
}]);
```

And this (after removing the above middleware from routes.php):
```php
class Kernel extends HttpKernel
{
    protected $middlewareGroups = [
        'web' => [
            \GrahamCampbell\HTMLMin\Http\Middleware\MinifyMiddleware::class,
        ],
    ];
}
```

And getting the same result documented in the issue.

Thanks.

**Comment by GrahamCampbell** [comment]
Did you run `php artisan config:cache`?

**Comment by bridgeport** [comment]
@GrahamCampbell No, I didn't. Using the `Kernel.php` approach, I just tried `php artisan config:cache` and the end result is the same.

What's interesting is this issue doesn't occur when using only blade minification and not middleware.

**Comment by GrahamCampbell** [comment]
Closing this as a no-fix. I d'no what's going on here I'm afraid.
