### ISSUE TITLE
Inline PHP comments within blade @php tags comments out succeeding code

### ISSUE THREAD

**Issue by bridgeport** [GrahamCampbell/Laravel-HTMLMin#56]
When automatic blade optimizations is set to true in the config file, the following:
```php
<?php
    // Just a comment
    $str = 'abc';
?>

@php
    // Just a comment
    $str = 'abc';
@endphp
```

Gets minified and compiled to:
```php
<?php
    // Just a comment
    $str = 'abc';
?>
 <?php // Just a comment $str = 'abc'; ?>
```

Using the regular `<?php ?>` tags is fine, but when using the blade `@php @endphp` tags, the inline comment and succeeding code gets pushed onto the same line and is commented out.

Not a huge deal as `/* */` can be used for comments instead. Just thought it worth pointing out.

Thanks.

**Comment by GrahamCampbell** [comment]
Thanks for the bug report.

**Comment by GrahamCampbell** [comment]
Guess all I can do here is to skip files that contain these comments.

**Comment by GrahamCampbell** [comment]
They're hard to detect though unless I actually tokenized the result.

**Comment by GrahamCampbell** [comment]
Ok, I've pushed a fix for this. Let me know if that works. :)

**Comment by bridgeport** [comment]
Fix works. Thanks @GrahamCampbell 

What's good is that instances of `//` won't hurt anything, while making sure the use of `/* */` still assures minification. I can discipline myself to use `/* */` when I want to make sure HTMLMin can still minify.

**Comment by GrahamCampbell** [comment]
Yeh. :)
