### ISSUE TITLE
Specific blade syntaxes are outputed as text

### ISSUE THREAD

**Issue by mtx-z** [GrahamCampbell/Laravel-HTMLMin#60]
Hey there,

thanks for this really good package.
I use the rappasoft boilerplate wich add some blade extensions ([url](https://github.com/rappasoft/laravel-5-boilerplate/wiki/2.-Access-Control)), but those extensions when used are outputed as plain text when minified.

Anyway to add those extensions to the minifier list ?

**Comment by GrahamCampbell** [comment]
Make sure packages register extensions in the boot method, and that you put this service provider before others that have extensions to register. If you don't do this, their extensions just get discarded.

**Comment by mtx-z** [comment]
That was it. Thanks a lot.
