### ISSUE TITLE
HTML Not minified without Middleware

### ISSUE THREAD

**Issue by lukasoppermann** [GrahamCampbell/Laravel-HTMLMin#61]
Hey @GrahamCampbell, 
maybe I am reading the docs wrong, but it does not do any minification of m html without the middleware.

I did the following:
- install
- add service provider
- publish config and set blade to true (also tried force to true)
- `artisan view:clear`

No result. Only when I add the middleware, will the html be minified. However, the way I understood it, the minification would normally be done when the blade templates are cached, correct?

So I should have cached and minified blade templates?

**Comment by GrahamCampbell** [comment]
I can't replicate. Blade minification is not complete anyway. It only does a fast poor job of the original template. The middleware is the only way to get full minification, but it comes at the performance penalty of getting the server to minify it. This could be more expensive than the network time.

**Comment by lukasoppermann** [comment]
So are you saying this package should not be used for blade/html minification?

**Comment by GrahamCampbell** [comment]
I'm saying it can for sure, but the results will be poor since it's just a fast minification at blade compile.

**Comment by GrahamCampbell** [comment]
The best results come from using the middleware.x

**Comment by lukasoppermann** [comment]
I see, so this should have worked with the steps I described above?

Are there any test on how much of a performance decrease this added middle ware adds? Just to know if the compression benefit outweighs this.

**Comment by GrahamCampbell** [comment]
No idea. You'll have to try it out. It depends.
