### ISSUE TITLE
The whole file that includes bad html is skipped from compression

### ISSUE THREAD

**Issue by SamAriafar** [GrahamCampbell/Laravel-HTMLMin#62]
You've used containsBadHtml function at BladeMinifier class to detect bad html and used shouldMinify function to decide whether skip the whole file that contains these pieces of codes. It was nicer if you took those segments out, minified them separately in case of need and put them back after compressing other codes.

**Comment by GrahamCampbell** [comment]
Skipping the whole file is probably fine I think. Fast enough.

**Comment by SamAriafar** [comment]
Well, that logic doesn't work for me. May I know why you have skipped inline scripts for example? Any specific reason?

**Comment by emielmolenaar** [comment]
> May I know why you have skipped inline scripts for example? Any specific reason?

Wondering about that too.

**Comment by SamAriafar** [comment]
@emielmolenaar If you like, you can use my patch on that: [https://github.com/SamAriafar/Laravel-HTMLMin/tree/patch-1](url)
