### ISSUE TITLE
don't minify markdown

### ISSUE THREAD

**Issue by hohl** [GrahamCampbell/Laravel-HTMLMin#65]
I'm using Laravels 5.4 new Markdown Mail framework, but this plugin keeps stripping away newlines in markdown files. I'd love to see a way to ignore markdown blade files.

**Comment by bramburn** [comment]
@hohl this will be fixed in the next merge

**Comment by wouterds** [comment]
It's indeed breaking the mails.

![Screenshot 1](https://up.kibakoapp.com/yX8MIEw3lL!#direct)

![Screenshot 2](https://up.kibakoapp.com/Gn6MR5QteJ!#direct)

**Comment by bramburn** [comment]
@wouterds try my branch 
https://github.com/bramburn/Laravel-HTMLMin

test it out and let me know if its working for you.

**Comment by GrahamCampbell** [comment]
Merged a good PR that addresses this. Will release as soon as travis ci catches up.
