### ISSUE TITLE
[Feature request] Exclude some View folders

### ISSUE THREAD

**Issue by jaysalvat** [GrahamCampbell/Laravel-HTMLMin#67]
Hello and thanks for this useful piece of code :)

I had a hard time to understand why my text/plain emails (in /resources/views/emails folder) were displayed without any line breaks in my inbox. :)
They were just minified as the rest of my HTML views.

It would be great to be able to exclude some folders or some files or any tips to help me?

Thanks a lot.

**Comment by d8vjork** [comment]
Same problem here.

**Comment by bramburn** [comment]
One option is to add a comment in the views you don't want to process so that the parser ignores it.
I'll try tinker with it in a different branch and see how that goes.

**Comment by bramburn** [comment]
I've just requested a pull to the main code. Hopefully it gets accepted.

**Comment by bramburn** [comment]
it works by added `<!-- skip.minification -->`

**Comment by d8vjork** [comment]
@bramburn Great! 👍 Meanwhile I was using [this fork](https://github.com/kabooodle/Laravel-HTMLMin/commit/b9f8bcb51ba28327667c7bded21e217ceeda12b6) but now I'll update

**Comment by jaysalvat** [comment]
Thanks a lot!
I will try soon 👍
