### ISSUE TITLE
Getting Auth not found error

### ISSUE THREAD

**Issue by emergingdzns** [GrahamCampbell/Laravel-HTMLMin#69]
I have just installed the HTMLMin and then added the class and facade to my app.php file.

If I try to run `php artisan vendor:publish` nothing happens. If I try to load the site, I get a 500 error.

My PHP logs the following error:
`[03-Apr-2017 07:40:45 America/Los_Angeles] PHP Fatal error:  Uncaught Exception: Class 'Auth' not found`

I can't figure out what is causing this. If I comment out the class and facade in the app.php it goes away and everything works as it was before I installed.

Any ideas on what I could be missing?

**Comment by GrahamCampbell** [comment]
No idea, sorry.

**Comment by GrahamCampbell** [comment]
What other packages do you have installed?
