### ISSUE TITLE
Doesn't work with Entrust (and maybe more)

### ISSUE THREAD

**Issue by Stichoza** [GrahamCampbell/Laravel-HTMLMin#79]
Outputs blade directives without compiling.

![2017-07-13 16 35 04](https://user-images.githubusercontent.com/1139050/28166511-3eda6538-67e9-11e7-8696-9867f54b40c3.jpg)

**Comment by GrahamCampbell** [comment]
I'd recommend not minifying the blade files then, and only using the minification middleware, or just not minfying at the laravel level, and getting nginx to minify.
